### ISSUE TITLE
Documentation: contentTypeOverride is not defined

### ISSUE THREAD

**Issue by deed02392** [rbartoli/express-content-type-override#18]
Example usage causes an error

**Comment by rbartoli** [comment]
If the error you get is the following, it means that you are missing the controller, however as you said it is just an usage example so you should tailor the code for your specific usage:

```bash
$ node .\index.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './controllers/registrationController'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\projects\test-express-app\index.js:4:30)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
